version: "3.8" # Versi贸n del formato de Docker Compose
services:
  api_users: # Servicio de la API de usuarios
    build: # Construcci贸n de la imagen
      context: . # Contexto de construcci贸n
      dockerfile: Dockerfile
    ports: # Puertos a exponer
      - "80:8081"
    command: ["java", "-jar", "/user_app/user_app.jar"] # Comando para ejecutar la aplicaci贸n
    env_file:
      - .env